import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { ClerkProvider } from '@clerk/nextjs'

import './globals.css'
import Header from '@/components/Header'
import { ConvexClientProvider } from '@/components/ConvexClientProvider'
import SyncUserWithConvex from '@/components/SyncUserWithConvex'
import { Toaster } from '@/components/ui/toaster'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})

const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})

export const metadata: Metadata = {
	title: 'Tiketr',
	description: 'Generated by Smart Corp',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ConvexClientProvider>
					<ClerkProvider>
						<Header />
						<SyncUserWithConvex />
						{children}
						<Toaster />
					</ClerkProvider>
				</ConvexClientProvider>
			</body>
		</html>
	)
}
